settings:
  content:
    merge: true

content:
  - name: playgym_practice
    label: "PRACTICE - PlayGym description"
    type: file
    path: src/content/playgym.json
    format: json
    operations:
      create: false
      rename: false
      delete: false
    fields:
      - name: title
        label: Program name
        type: string
        readonly: true

      - name: tagline
        label: Short description
        type: text
        required: true

      - name: about
        label: About PlayGym paragraphs
        type: text
        list: true