import { practiceSiteUrl } from '../../practice-origin.mjs';

export const siteConfig = {
  phone: '61435060352', // Trident Gymnastics phone number (0435 060 352)
  whatsappMessage: 'Hi%20Trident%20Gymnastics%20-%20holiday%20program%20enquiry',
  siteName: 'Trident Gymnastics',
  siteDescription: 'Ringwood gymnastics club offering preschool gymnastics, EduGym, UrbanGym, PlayGym, holiday programs and birthday parties for children and families.',
  // Canonical URLs stay on the separate practice host.
  siteUrl: practiceSiteUrl,
  email: 'info@tridentgymnastics.com.au',
  address: '4/8-10 Maroondah Highway, Ringwood VIC 3134',
  streetAddress: 'Unit 4, 8-10 Maroondah Highway',
  addressLocality: 'Ringwood',
  addressRegion: 'VIC',
  postalCode: '3134',
  addressCountry: 'AU',
  // Verified against both the Google Business listing and OpenStreetMap, which
  // agree this is the sports_hall at 8-10 Maroondah Highway. The previous pair
  // (-37.81419, 145.22895) sat ~1.26km away on Ringwood Town Square, which put
  // the structured-data geo at odds with the postal address above.
  geo: {
    latitude: -37.8182408,
    longitude: 145.2154716
  },
  // Public place listing, used for "open in Maps" links.
  mapsUrl: 'https://maps.app.goo.gl/kWSFW1MAkZkoX3gu8',
  // Keyless Google embed, as generated by Maps itself. Searching by business
  // name means the pin reads "Trident Gymnastics" with its rating instead of a
  // bare street address. Kept literal: the !-delimited pb payload is Google's
  // own format and does not survive being rebuilt from encodeURIComponent.
  mapsEmbedUrl:
    'https://www.google.com/maps/embed?pb=!1m3!2m1!1sTrident+Gymnastics,+8-10+Maroondah+Highway,+Ringwood+VIC+3134!6i16',
  nearbyAreas: ['Ringwood', 'Ringwood East', 'Croydon', 'Heathmont', 'Mitcham', 'Nunawading', 'Bayswater', 'Maroondah'],
  defaultImage: `${practiceSiteUrl}/Images/compressed-Logo.webp`,
  facebook: 'https://www.facebook.com/tridentgymnastics',
  instagram: 'https://www.instagram.com/tridentgymnastics/',
  operatingHours: {
    monday: { open: '9:30 AM', close: '12:30 PM', evening: '3:30 PM - 7:30 PM' },
    tuesday: { open: '9:30 AM', close: '12:30 PM', evening: '3:30 PM - 7:30 PM' },
    wednesday: { open: '9:30 AM', close: '12:30 PM', evening: '3:30 PM - 7:30 PM' },
    thursday: { open: '9:30 AM', close: '12:30 PM', evening: '3:30 PM - 7:30 PM' },
    friday: { open: '9:30 AM', close: '12:30 PM', evening: '3:30 PM - 7:30 PM' },
    saturday: { open: '7:30 AM', close: '4:30 PM', evening: null },
    sunday: { open: null, close: null, evening: null }
  }
};
